#!/usr/bin/env python3
"""
setup_secrets.py - Автоматическая генерация секретов для ARGOS

Использование:
    python setup_secrets.py              # Интерактивный режим
    python setup_secrets.py --auto       # Автоматический режим
    python setup_secrets.py --check      # Проверка существующих секретов
"""

import os
import sys
import secrets
import hashlib
from pathlib import Path


def generate_secret(length=32):
    """Генерирует криптографически стойкий секрет."""
    return secrets.token_hex(length)


def check_env_exists():
    """Проверяет существование .env файла."""
    return Path(".env").exists()


def load_env():
    """Загружает существующие переменные из .env."""
    env_vars = {}
    if check_env_exists():
        with open(".env", "r") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, value = line.split("=", 1)
                    env_vars[key.strip()] = value.strip()
    return env_vars


def save_env(env_vars):
    """Сохраняет переменные в .env."""
    with open(".env", "w") as f:
        f.write("# ARGOS Universal OS - Environment Configuration\n")
        f.write("# Generated by setup_secrets.py\n")
        f.write("# DO NOT COMMIT THIS FILE TO VERSION CONTROL!\n\n")

        f.write("# ─── API Keys ───────────────────────────────────────────────\n")
        f.write(
            f"GEMINI_API_KEY={env_vars.get('GEMINI_API_KEY', 'your_gemini_api_key_here')}\n"
        )
        f.write(
            f"TELEGRAM_BOT_TOKEN={env_vars.get('TELEGRAM_BOT_TOKEN', 'your_telegram_bot_token_here')}\n"
        )
        f.write(f"USER_ID={env_vars.get('USER_ID', 'your_telegram_user_id_here')}\n\n")

        f.write("# ─── Security Secrets (AUTO-GENERATED) ─────────────────────\n")
        f.write(f"ARGOS_NETWORK_SECRET={env_vars.get('ARGOS_NETWORK_SECRET', '')}\n")
        f.write(f"ARGOS_MASTER_KEY={env_vars.get('ARGOS_MASTER_KEY', '')}\n\n")

        f.write("# ─── Optional API Keys ─────────────────────────────────────\n")
        f.write(
            f"# OPENAI_API_KEY={env_vars.get('OPENAI_API_KEY', 'your_openai_key_here')}\n"
        )
        f.write(
            f"# GROK_API_KEY={env_vars.get('GROK_API_KEY', 'your_grok_key_here')}\n"
        )
        f.write(
            f"# WATSONX_API_KEY={env_vars.get('WATSONX_API_KEY', 'your_watsonx_key_here')}\n"
        )


def check_secrets():
    """Проверяет существующие секреты."""
    if not check_env_exists():
        print("❌ Файл .env не найден")
        return False

    env_vars = load_env()
    issues = []

    # Проверка обязательных секретов
    required = ["ARGOS_NETWORK_SECRET", "ARGOS_MASTER_KEY"]
    for key in required:
        value = env_vars.get(key, "")
        if (
            not value
            or value.startswith("your_")
            or value == "generate_unique_secret_with_openssl_rand_hex_32"
        ):
            issues.append(f"❌ {key}: не установлен или использует placeholder")
        elif len(value) != 64:
            issues.append(f"⚠️  {key}: длина {len(value)} символов (ожидается 64)")
        else:
            print(f"✅ {key}: установлен корректно")

    # Проверка API ключей
    api_keys = ["GEMINI_API_KEY", "TELEGRAM_BOT_TOKEN", "USER_ID"]
    for key in api_keys:
        value = env_vars.get(key, "")
        if not value or value.startswith("your_"):
            print(f"⚠️  {key}: не установлен")
        else:
            print(f"✅ {key}: установлен")

    if issues:
        print("\n⚠️  Найдены проблемы:")
        for issue in issues:
            print(f"  {issue}")
        return False

    print("\n✅ Все секреты настроены корректно!")
    return True


def interactive_setup():
    """Интерактивная настройка секретов."""
    print("🔐 ARGOS Security Setup")
    print("=" * 60)

    env_vars = load_env() if check_env_exists() else {}

    # Генерация секретов
    print("\n📝 Генерация криптографических секретов...")

    if not env_vars.get("ARGOS_NETWORK_SECRET") or env_vars[
        "ARGOS_NETWORK_SECRET"
    ].startswith("your_"):
        network_secret = generate_secret(32)
        env_vars["ARGOS_NETWORK_SECRET"] = network_secret
        print(f"✅ ARGOS_NETWORK_SECRET: {network_secret[:16]}...{network_secret[-8:]}")
    else:
        print(f"✅ ARGOS_NETWORK_SECRET: уже установлен")

    if not env_vars.get("ARGOS_MASTER_KEY") or env_vars["ARGOS_MASTER_KEY"].startswith(
        "your_"
    ):
        master_key = generate_secret(32)
        env_vars["ARGOS_MASTER_KEY"] = master_key
        print(f"✅ ARGOS_MASTER_KEY: {master_key[:16]}...{master_key[-8:]}")
    else:
        print(f"✅ ARGOS_MASTER_KEY: уже установлен")

    # API ключи
    print("\n📝 Настройка API ключей...")
    print("(Нажмите Enter, чтобы оставить текущее значение)")

    for key in ["GEMINI_API_KEY", "TELEGRAM_BOT_TOKEN", "USER_ID"]:
        current = env_vars.get(key, "")
        if current and not current.startswith("your_"):
            display = (
                f"{current[:8]}...{current[-4:]}" if len(current) > 12 else current
            )
            print(f"  {key}: {display} (установлен)")
        else:
            value = input(f"  {key}: ").strip()
            if value:
                env_vars[key] = value

    # Сохранение
    save_env(env_vars)
    print("\n✅ Конфигурация сохранена в .env")

    # Защита файла
    try:
        os.chmod(".env", 0o600)
        print("✅ Установлены права доступа 600 (только владелец)")
    except Exception as e:
        print(f"⚠️  Не удалось установить права доступа: {e}")

    print("\n" + "=" * 60)
    print("✅ Настройка завершена!")
    print("\n📋 Следующие шаги:")
    print("  1. Проверьте .env и добавьте недостающие API ключи")
    print("  2. Запустите: python genesis.py")
    print("  3. Запустите: python main.py")


def auto_setup():
    """Автоматическая настройка (только секреты, без API ключей)."""
    print("🔐 ARGOS Auto Setup")
    print("=" * 60)

    env_vars = load_env() if check_env_exists() else {}

    # Генерация только секретов
    changed = False

    if not env_vars.get("ARGOS_NETWORK_SECRET") or env_vars[
        "ARGOS_NETWORK_SECRET"
    ].startswith("your_"):
        env_vars["ARGOS_NETWORK_SECRET"] = generate_secret(32)
        print("✅ Сгенерирован ARGOS_NETWORK_SECRET")
        changed = True

    if not env_vars.get("ARGOS_MASTER_KEY") or env_vars["ARGOS_MASTER_KEY"].startswith(
        "your_"
    ):
        env_vars["ARGOS_MASTER_KEY"] = generate_secret(32)
        print("✅ Сгенерирован ARGOS_MASTER_KEY")
        changed = True

    if changed:
        save_env(env_vars)
        print("✅ Секреты сохранены в .env")

        try:
            os.chmod(".env", 0o600)
            print("✅ Установлены права доступа 600")
        except:
            pass
    else:
        print("✅ Все секреты уже настроены")

    print("\n⚠️  Не забудьте добавить API ключи в .env:")
    print("  - GEMINI_API_KEY")
    print("  - TELEGRAM_BOT_TOKEN")
    print("  - USER_ID")


def main():
    """Главная функция."""
    if len(sys.argv) > 1:
        arg = sys.argv[1]
        if arg == "--auto":
            auto_setup()
        elif arg == "--check":
            check_secrets()
        elif arg in ["--help", "-h"]:
            print(__doc__)
        else:
            print(f"❌ Неизвестный аргумент: {arg}")
            print(__doc__)
    else:
        interactive_setup()


if __name__ == "__main__":
    main()
