"""
flasher.py — Smart Flasher: авто-детект USB чипов и прошивка
Поддерживает: ESP32, RP2040, STM32
Команды: найди usb чипы | умная прошивка [порт] | прошей gateway [порт] [цель]
"""
import os
import shutil
import subprocess
import time
from datetime import datetime

try:
    import serial.tools.list_ports
except Exception:
    serial = None

CHIP_SIGNATURES = {
    "esp32": {
        "vid_pid":  {(0x10C4, 0xEA60), (0x1A86, 0x7523), (0x0403, 0x6001)},
        "keywords": ("cp210", "ch340", "ft232", "esp32"),
    },
    "rp2040": {
        "vid_pid":  {(0x2E8A, 0x0005), (0x2E8A, 0x000A)},
        "keywords": ("rp2040", "raspberry pi pico"),
    },
    "stm32": {
        "vid_pid":  {(0x0483, 0x5740), (0x0483, 0xDF11)},
        "keywords": ("stm32", "stlink", "dfu"),
    },
}

FIRMWARE_DIR = "assets/firmware"
SMART_FIRMWARES = {
    "gateway":        {"kind": "auto", "description": "Авто-заготовка под чип"},
    "air_tag":        {"kind": "auto", "description": "Авто-заготовка air_tag"},
    "tasmota_relay":  {"kind": "bin",  "path": os.path.join(FIRMWARE_DIR, "tasmota_relay.bin")},
    "tasmota_sensor": {"kind": "bin",  "path": os.path.join(FIRMWARE_DIR, "tasmota_sensor.bin")},
}


class AirFlasher:

    # ── Список доступных прошивок ─────────────────────────
    def list_available_firmwares(self) -> list[str]:
        names = []
        for fw_name, meta in SMART_FIRMWARES.items():
            if meta.get("kind") == "auto":
                names.append(f"{fw_name} (auto)")
            else:
                path = meta.get("path", "")
                exists = path and os.path.exists(path)
                names.append(fw_name if exists else f"{fw_name} (ожидается {path})")
        return names

    # ── COM-порты ────────────────────────────────────────
    def _comports(self):
        if serial is None:
            return []
        try:
            return list(serial.tools.list_ports.comports())
        except Exception:
            return []

    def scan_ports(self) -> list[str]:
        ports = [p.device for p in self._comports()]
        return ports if ports else ["Устройства не обнаружены"]

    # ── Определение чипа ─────────────────────────────────
    def _guess_chip(self, port_info) -> str:
        vid  = getattr(port_info, "vid",  None)
        pid  = getattr(port_info, "pid",  None)
        desc = (getattr(port_info, "description", "") or "").lower()
        hwid = (getattr(port_info, "hwid", "") or "").lower()
        for chip, sig in CHIP_SIGNATURES.items():
            if (vid, pid) in sig["vid_pid"]:
                return chip
            if any(k in desc or k in hwid for k in sig["keywords"]):
                return chip
        return "unknown"

    def detect_usb_chips(self) -> list[dict]:
        devices = []
        for p in self._comports():
            devices.append({
                "port":        p.device,
                "chip":        self._guess_chip(p),
                "description": getattr(p, "description", "") or "Unknown",
                "vid":         getattr(p, "vid", None),
                "pid":         getattr(p, "pid", None),
            })
        return devices

    def detect_usb_chips_report(self) -> str:
        devices = self.detect_usb_chips()
        if not devices:
            return "📡 USB-устройства не найдены."
        lines = ["📡 SMART FLASHER — USB ДЕТЕКТ:"]
        for d in devices:
            vp = "n/a" if d["vid"] is None else f"{d['vid']:04x}:{d['pid']:04x}"
            lines.append(f"  • {d['port']} | chip={d['chip']} | {vp} | {d['description']}")
        return "\n".join(lines)

    # ── Заготовка прошивки ───────────────────────────────
    def _build_firmware_stub(self, chip: str, target_name: str = "gateway") -> str:
        os.makedirs(FIRMWARE_DIR, exist_ok=True)
        stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        if chip in {"esp32", "rp2040", "stm32"}:
            path = f"{FIRMWARE_DIR}/auto_{target_name}_{chip}_{stamp}.ino"
            code = (
                "// Auto-generated by Argos Smart Flasher\n"
                "void setup() {\n"
                "  Serial.begin(115200);\n"
                "  pinMode(LED_BUILTIN, OUTPUT);\n"
                "}\n\n"
                "void loop() {\n"
                "  digitalWrite(LED_BUILTIN, HIGH); delay(250);\n"
                "  digitalWrite(LED_BUILTIN, LOW);  delay(250);\n"
                "}\n"
            )
            with open(path, "w") as f:
                f.write(code)
            return path
        path = f"{FIRMWARE_DIR}/auto_{target_name}_{stamp}.bin"
        with open(path, "wb") as f:
            f.write(b"")
        return path

    def _resolve_firmware_path(self, chip: str, target_name: str) -> tuple[str, str | None]:
        key  = (target_name or "gateway").strip().lower()
        meta = SMART_FIRMWARES.get(key)
        if meta and meta.get("kind") == "bin":
            fp = str(meta.get("path", ""))
            if not os.path.exists(fp):
                return "", f"⚠️ Бинарник '{key}' не найден: {fp}"
            return fp, None
        return self._build_firmware_stub(chip, target_name=key), None

    def _tool_exists(self, name: str) -> bool:
        return shutil.which(name) is not None

    def _run(self, cmd: list[str], timeout: int = 180) -> tuple[int, str]:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
        out  = (proc.stdout or "") + (("\n" + proc.stderr) if proc.stderr else "")
        return proc.returncode, out.strip()

    # ── Прошивка ─────────────────────────────────────────
    def flash_chip(self, port: str, chip: str, firmware_path: str) -> str:
        if chip == "esp32":
            tool = shutil.which("esptool.py") or shutil.which("esptool")
            if not tool:
                return "❌ esptool не найден: pip install esptool"
            if not firmware_path.lower().endswith(".bin"):
                return "⚠️ ESP32 требует .bin файл."
            code, out = self._run([tool, "--port", port, "--baud", "921600",
                                   "write_flash", "0x1000", firmware_path])
            return f"✅ ESP32 прошит: {port}" if code == 0 else f"❌ ESP32 error:\n{out[:400]}"

        if chip in {"rp2040", "stm32"}:
            if not self._tool_exists("platformio"):
                return "❌ PlatformIO не найден: pip install platformio"
            code, out = self._run(["platformio", "run", "-t", "upload",
                                   "--upload-port", port])
            return f"✅ {chip.upper()} прошит" if code == 0 else f"❌ {chip} error:\n{out[:400]}"

        return f"⚠️ Чип '{chip}' не распознан."

    def smart_flash(self, port: str = None, target_name: str = "gateway") -> str:
        devices = self.detect_usb_chips()
        if not devices:
            return "❌ Нет USB-устройств для прошивки."
        selected = None
        if port:
            for d in devices:
                if d["port"] == port:
                    selected = d; break
            if not selected:
                return f"❌ Порт {port} не найден."
        else:
            selected = devices[0]

        fw, err = self._resolve_firmware_path(selected["chip"], target_name)
        available = ", ".join(self.list_available_firmwares())
        if not fw:
            return (f"⚡ SMART FLASHER\n"
                    f"  Порт: {selected['port']}\n"
                    f"  Чип: {selected['chip']}\n"
                    f"  Ошибка: {err}\n"
                    f"  Доступные прошивки: {available}")

        result = self.flash_chip(selected["port"], selected["chip"], fw)
        return (f"⚡ SMART FLASHER\n"
                f"  Порт: {selected['port']}\n"
                f"  Чип: {selected['chip']}\n"
                f"  Прошивка: {fw}\n"
                f"  Доступные: {available}\n"
                f"  Результат: {result}")

    def flash_air_tag(self, port):
        return self.smart_flash(port=port, target_name="air_tag")


# Алиас для обратной совместимости
ArgosFlasher = AirFlasher
