import os
import time
import shutil
import subprocess
from datetime import datetime

try:
    import serial.tools.list_ports
except Exception:  # pragma: no cover
    serial = None


CHIP_SIGNATURES = {
    "esp32": {
        "vid_pid": {(0x10C4, 0xEA60), (0x1A86, 0x7523), (0x0403, 0x6001)},
        "keywords": ("cp210", "ch340", "ft232", "esp32"),
    },
    "rp2040": {
        "vid_pid": {(0x2E8A, 0x0005), (0x2E8A, 0x000A)},
        "keywords": ("rp2040", "raspberry pi pico"),
    },
    "stm32": {
        "vid_pid": {(0x0483, 0x5740), (0x0483, 0xDF11)},
        "keywords": ("stm32", "stlink", "dfu"),
    },
}


class AirFlasher:
    def _comports(self):
        if serial is None:
            return []
        try:
            return list(serial.tools.list_ports.comports())
        except Exception:
            return []

    def _guess_chip(self, port_info) -> str:
        vid = getattr(port_info, "vid", None)
        pid = getattr(port_info, "pid", None)
        desc = (getattr(port_info, "description", "") or "").lower()
        hwid = (getattr(port_info, "hwid", "") or "").lower()

        for chip, sig in CHIP_SIGNATURES.items():
            if (vid, pid) in sig["vid_pid"]:
                return chip
            if any(k in desc or k in hwid for k in sig["keywords"]):
                return chip
        return "unknown"

    def scan_ports(self):
        ports = [p.device for p in self._comports()]
        return ports if ports else ["Устройства не обнаружены"]

    def detect_usb_chips(self):
        devices = []
        for p in self._comports():
            devices.append({
                "port": p.device,
                "chip": self._guess_chip(p),
                "description": getattr(p, "description", "") or "Unknown",
                "vid": getattr(p, "vid", None),
                "pid": getattr(p, "pid", None),
            })
        return devices

    def detect_usb_chips_report(self) -> str:
        devices = self.detect_usb_chips()
        if not devices:
            return "📡 USB-устройства не найдены."
        lines = ["📡 SMART FLASHER — USB ДЕТЕКТ:"]
        for dev in devices:
            vp = "n/a" if dev["vid"] is None or dev["pid"] is None else f"{dev['vid']:04x}:{dev['pid']:04x}"
            lines.append(f"  • {dev['port']} | chip={dev['chip']} | vid:pid={vp} | {dev['description']}")
        return "\n".join(lines)

    def _build_firmware_stub(self, chip: str, target_name: str = "gateway") -> str:
        os.makedirs("assets/firmware", exist_ok=True)
        stamp = datetime.now().strftime("%Y%m%d_%H%M%S")

        if chip in {"esp32", "rp2040", "stm32"}:
            path = f"assets/firmware/auto_{target_name}_{chip}_{stamp}.ino"
            code = (
                "// Auto-generated by Argos Smart Flasher\n"
                "void setup() {\n"
                "  Serial.begin(115200);\n"
                "  pinMode(LED_BUILTIN, OUTPUT);\n"
                "}\n\n"
                "void loop() {\n"
                "  digitalWrite(LED_BUILTIN, HIGH);\n"
                "  delay(250);\n"
                "  digitalWrite(LED_BUILTIN, LOW);\n"
                "  delay(250);\n"
                "}\n"
            )
            with open(path, "w", encoding="utf-8") as f:
                f.write(code)
            return path

        path = f"assets/firmware/auto_{target_name}_{stamp}.bin"
        with open(path, "wb") as f:
            f.write(b"")
        return path

    def _tool_exists(self, name: str) -> bool:
        return shutil.which(name) is not None

    def _run(self, cmd: list[str], timeout: int = 180) -> tuple[int, str]:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
        out = (proc.stdout or "") + (("\n" + proc.stderr) if proc.stderr else "")
        return proc.returncode, out.strip()

    def flash_chip(self, port: str, chip: str, firmware_path: str) -> str:
        if chip == "esp32":
            tool = shutil.which("esptool.py") or shutil.which("esptool")
            if not tool:
                return "❌ esptool не найден. Установи: pip install esptool"
            if not firmware_path.lower().endswith(".bin"):
                return "⚠️ Для ESP32 нужен .bin. Сначала собери бинарник или передай готовый файл."
            code, out = self._run([tool, "--port", port, "--baud", "921600", "write_flash", "0x1000", firmware_path])
            return f"✅ ESP32 прошит: {port}" if code == 0 else f"❌ ESP32 flash error:\n{out[:400]}"

        if chip in {"rp2040", "stm32"}:
            if not self._tool_exists("platformio"):
                return "❌ PlatformIO CLI не найден. Установи: pip install platformio"
            if firmware_path.lower().endswith(".ino"):
                return (
                    f"⚠️ Для {chip.upper()} создан скетч: {firmware_path}\n"
                    "Сборка/заливка через PlatformIO требует проекта (platformio.ini)."
                )
            code, out = self._run(["platformio", "run", "-t", "upload", "--upload-port", port])
            return f"✅ {chip.upper()} прошит: {port}" if code == 0 else f"❌ {chip.upper()} flash error:\n{out[:400]}"

        return f"⚠️ Чип '{chip}' не распознан. Прошивка вручную: {firmware_path}"

    def smart_flash(self, port: str = None, target_name: str = "gateway") -> str:
        devices = self.detect_usb_chips()
        if not devices:
            return "❌ Нет USB-устройств для прошивки."

        selected = None
        if port:
            for dev in devices:
                if dev["port"] == port:
                    selected = dev
                    break
            if not selected:
                return f"❌ Порт {port} не найден. Доступно: {', '.join(d['port'] for d in devices)}"
        else:
            selected = devices[0]

        fw = self._build_firmware_stub(selected["chip"], target_name=target_name)
        flash_result = self.flash_chip(selected["port"], selected["chip"], fw)
        return (
            "⚡ SMART FLASHER\n"
            f"  Порт: {selected['port']}\n"
            f"  Чип: {selected['chip']}\n"
            f"  Заготовка прошивки: {fw}\n"
            f"  Результат: {flash_result}"
        )

    def flash_air_tag(self, port):
        if port not in self.scan_ports():
            return "Порт недоступен."
        time.sleep(2)  # Обратная совместимость со старым API
        return self.smart_flash(port=port, target_name="air_tag")
